#!/usr/bin/env python3
import os
import runpy

SCRIPT = os.path.join(
    os.path.dirname(__file__),
    "harmonytime-classes",
    "scripts",
    "harmonytime_classes.py",
)
runpy.run_path(SCRIPT, run_name="__main__")
